### ISSUE TITLE
Styles seem to duplicate

### ISSUE THREAD

**Issue by drcmda** [tizmagik/react-csjs#4] opened 2016-09-22 18:36 UTC
``` js
const NavLink = ({ name, to, classes }) => (
    <Link activeClass={classes.active.className} to={to} smooth={true} spy={true}>
        { name || to }
    </Link>
)

var styles = csjs`
    .active {
        background-color: #dfdfdf;
        color: white;
    }
`;

export default withStyles(styles)(NavLink);
```

There are 5 NavLinks mounted, all have injected the same style with the same key. Once one is active, there are 5 rules overriding each other. 

![screenshot](http://i.imgur.com/pDjuqMy.jpg)

Am i doing something wrong? How can this be prevented?

**Comment by tizmagik** [comment] 2016-09-22 19:11
@drcmda thanks for reporting this!

I don't think you're doing anything wrong. The issue is that we're not using a singleton pattern for the CSJS styles to be mounted and there's no way to currently pass in a singleton object to make sure we don't mount a style that's already been mounted.

I will take a look and push a fix for this hopefully soon, any help appreciated of course! Thanks!

**Comment by tizmagik** [comment] 2016-09-22 20:20
@rtsao I wanted to ping you on this issue to see if you have recommendation here. I think the way to solve this is to use a singleton pattern with a cache object that caches each CSS declaration. In the case where there's a cache-hit, it won't insert that style. Is there a better, more idiomatic `csjs` way to do this that you would recommend?

**Comment by drcmda** [comment] 2016-09-23 07:29
@tizmagik Good idea! Maybe a simple hashmap at the module level is enough. It then counts references. Once refs are down to zero through all the unmounts the style tag gets removed. If refs are above 1 the mounting function would skip the injection part. Just needs a unique id for the generated css.

**Comment by drcmda** [comment] 2016-09-23 08:44
i made a PR here: https://github.com/tizmagik/react-csjs/pull/5

Solves it for me. It doesn't even need a hash or id since you already have one in the form of the DecoratedComponent.

![screenshot](http://i.imgur.com/kYLwPpq.jpg)

**Comment by tizmagik** [comment] 2016-09-23 10:37
Ah, brilliant! I didn't think to use the DecoratedComponent as the cache key. Very nice.

**Comment by drcmda** [comment] 2016-09-23 18:09
Awesome, thanks for merging! Could you push the revision to npm as well?

**Comment by tizmagik** [comment] 2016-09-23 18:11
Yeap, about to push `v1.1.0` shortly!

Also, if you're interested in helping maintain this I'd be happy to add you as a collaborator. Let me know!

**Comment by tizmagik** [comment] 2016-09-23 18:33
@drcmda `v1.1.0` published.

**Closed as completed by tizmagik** 2016-09-23 18:33 UTC
